<a href="https://colab.research.google.com/github/patilo/Python-Data-Analyst/blob/main/ejercicios_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ventas de Supermercado
#Imagina que tienes una matriz donde las filas son 3 tiendas y las columnas son 4 meses de ventas.

In [18]:
import numpy as np

# Ventas (Filas: Tiendas | Columnas: Meses)
ventas = np.array([
    [100, 120, 110, 150], # Tienda A
    [500, 50, 60, 70],    # Tienda B (El 500 es un outlier)
    [200, 210, 190, 205]  # Tienda C
])

In [21]:
# --- PROMEDIOS (MEAN) ---
# Promedio de ventas por MES (colapsa las filas)
promedio_mes = np.mean(ventas, axis=0)
print(promedio_mes)

# Resultado: [266.6, 126.6, 120.0, 141.6]

# Promedio de ventas por TIENDA (colapsa las columnas)
promedio_tienda = np.mean(ventas, axis=1)
print(promedio_tienda)
# Resultado: [120.0, 170.0, 201.2]

# --- MEDIANA (MEDIAN) ---
# Muy útil para la Tienda B que tiene un 500 (valor muy alto)
mediana_tienda_b = np.median(ventas[1, :])
print(mediana_tienda_b)
# Resultado: 65.0 (Mucho más realista que su promedio de 170)

# --- DESVIACIÓN ESTÁNDAR (STD) ---
# ¿Qué tienda es más "estable" en sus ventas?
estabilidad = np.std(ventas, axis=1)
print(estabilidad)
# La Tienda C tendrá un número bajo (ventas parecidas: 190, 200, 210)
# La Tienda B tendrá un número altísimo (por el salto de 500 a 50)


[266.66666667 126.66666667 120.         141.66666667]
[120.   170.   201.25]
65.0
[ 18.70828693 190.65675965   7.39509973]


Optimización de Costos en la Nube (GCP/AWS).

Imagina que administras 5 servidores y tienes los datos de consumo de recursos (en GB de RAM) durante los 7 días de la semana. Necesitas saber cuál servidor está sobredimensionado (gastando dinero de más) y cuál está en riesgo de colapsar.

In [22]:
#Cada fila es un servidor, cada columna es un día de la semana.
import numpy as np

# Consumo de RAM en GB (5 servidores x 7 días)
consumo = np.array([
    [16, 15, 14, 16, 15, 16, 14], # Servidor 1: Estable y alto
    [4, 32, 4, 5, 30, 4, 4],      # Servidor 2: Picos inestables (Inestable)
    [2, 2, 3, 2, 2, 3, 2],        # Servidor 3: Consumo mínimo (Sobredimensionado)
    [12, 12, 13, 12, 12, 13, 12], # Servidor 4: Estable
    [8, 9, 8, 35, 8, 9, 8]        # Servidor 5: Un solo pico crítico
])

In [34]:
#axis 1 consumo maximo de la ram
consumo_maximo_por_servidor = np.max(consumo, axis=1)
print(consumo_maximo_por_servidor)
print("----------------------")
#axis 1 consumo promedio de la ram
consumo_maximo_por_servidor = np.mean(consumo, axis=1)
print(consumo_maximo_por_servidor)
print("----------------------")
#axis estabilidad de la ram
consumo_maximo_por_dia = np.std(consumo, axis=1)
print(consumo_maximo_por_dia)


[16 32  3 13 35]
----------------------
[15.14285714 11.85714286  2.28571429 12.28571429 12.14285714]
----------------------
[ 0.83299313 12.12351401  0.45175395  0.45175395  9.34159013]


Análisis con axis=1 (Por Servidor)
Queremos saber el comportamiento de cada máquina a lo largo de la semana.

np.mean(consumo, axis=1): Nos da el consumo promedio. Si el promedio del Servidor 3 es muy bajo (2.2 GB) y tiene contratados 16 GB, estás perdiendo plata.

np.std(consumo, axis=1): Aquí detectamos la estabilidad.

El Servidor 1 tendrá una desviación estándar baja (cercana a 0.8), lo que significa que es predecible.

El Servidor 2 tendrá una desviación alta (~12.5), lo que indica que algo raro pasa (procesos que se disparan).

In [35]:
#analisis por dia axis 0
consumo_maximo_por_dia = np.median(consumo, axis=0)
print(consumo_maximo_por_dia)

[ 8. 12.  8. 12. 12.  9.  8.]


La Regla de Oro
axis=0 (Vertical): La operación se hace hacia abajo. Imagina que pones una prensa hidráulica arriba de la matriz y la aplastas contra el suelo. El resultado tendrá el ancho de las columnas.

axis=1 (Horizontal): La operación se hace hacia el lado. Imagina que empujas la matriz contra una pared a la derecha. El resultado tendrá el alto de las filas.