# Numpy
acontinuacion veremos como utilizar la paqueteria 
de numpy, nos permite hacer metodos para matrices, arreglos y vectores
ejemplo crearemos una matriz de 3x3

In [6]:
# vector de dim9 importando numpy
import numpy as np

a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
#aqui a nuestra array que le asignamos 9 valores
#lo pasamos a una matriz de 3x3
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
# crearemos una lista de numeros primos
numeros_primos=[2,3,5,7,11,13]
numeros_primos

[2, 3, 5, 7, 11, 13]

In [9]:
#creamos un array de numeros primos
array_primos=np.array(numeros_primos)
array_primos


array([ 2,  3,  5,  7, 11, 13])

In [10]:
#creamos array con arange
array_numeros=np.arange(10)
array_numeros

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#creamos array numeros pares del 0 al 20 y 2 en 2
array_pares=np.arange(0,20,2)
array_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
#creamos un array de 2 dimensiones 2 filas y 5 columnas
array_pares.reshape(2,5)


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

# veamos la suma y estadistica
Acontinuacion veremos la suma, promedio y moda
con numpy, se pueden ver muchas mas funciones
con estadisticas
creamos nuestro array de numeros primos

In [12]:
array_primos

array([ 2,  3,  5,  7, 11, 13])

In [13]:
#hacemos una suma de arrays
array_primos.sum()

41

In [14]:
#sacamos el promedio del array
array_primos.mean()

6.833333333333333

In [15]:
#sacamos la varianza del array
array_primos.var()

16.13888888888889

In [17]:
#ordenar un array
array_desordenado=np.array([10,9,11,29,18,16,0,1,2,3])
array_desordenado

array([10,  9, 11, 29, 18, 16,  0,  1,  2,  3])

In [18]:
#ordenado de menor a mayor
np.sort(array_desordenado)

array([ 0,  1,  2,  3,  9, 10, 11, 16, 18, 29])

In [19]:
#ordenado de mayor a menor
#usamos con el negativo (-)
-np.sort(-array_desordenado)

array([29, 18, 16, 11, 10,  9,  3,  2,  1,  0])

In [21]:
#creamos un array de 2dmin y 5col
#le diremos que sea del 0 al 20 y vaya de 2 en 2

a=np.arange(0,20,2).reshape(2,5)
a

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

# ahora veremos como seleccionar
un elemento del array, recordar que la primera fila es 0 siempre

In [22]:
#seleccionamos la fila y columna 0
a[0,0]

0

In [23]:
#seleccionamos la fila 1 y la columna 4
a[1,4]

18

In [24]:
#seleccionamos todo de la fila 1
a[1,:]

array([10, 12, 14, 16, 18])

In [25]:
#ahora por columna
a[:,1]

array([ 2, 12])

# utilizaremos las condiciones dentro
# del array, 1 vez es boolean y si insertamos
# nuevamente el array nos muestra los num

In [26]:
array_desordenado

array([10,  9, 11, 29, 18, 16,  0,  1,  2,  3])

In [28]:
array_desordenado<20

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [30]:
array_desordenado[array_desordenado<20]

array([10,  9, 11, 18, 16,  0,  1,  2,  3])